repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -s tests/testproject/testapp -c tests/testproject/pytest.ini
        language: system
        pass_filenames: false
        types_or: [python, html]
